# Generated by Django 6.1.1 on 2026-10-07 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='costo_compra',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Costo de Compra'),
        ),
        migrations.AddField(
            model_name='producto',
            name='en_oferta',
            field=models.BooleanField(default=False, verbose_name='¿En Oferta / Promoción?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_oferta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de Oferta'),
        ),
    ]
